apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-mongo
  namespace: ns-posthub-local
  labels:
    name: comments-mongo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: comments-mongo
  template:
    metadata:
      labels:
        name: comments-mongo
    spec:
      containers:
      - image: mongo:5.0
        name: comments-mongo
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "1500m"
            memory: "2500M"    
        ports:
        - containerPort: 27017
          name: comments-mongo

---
kind: Service
apiVersion: v1
metadata:
  name: comments-mongo-service
  namespace: ns-posthub-local
spec:
  selector:
    name: comments-mongo
  type: ClusterIP
  ports:
  - name: comments-mongo
    port: 27020
    targetPort: 27017
